logging:
    levelEntity:
        org:
            springframework:
                web: TRACE
spring:
    datasource:
        password: root
        username: root
        url: jdbc:mysql://localhost:3306/monitoring-system-db?useSSL=false&serverTimezone=UTC
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
        show-sql: true
